### PR TITLE
Methods optimization

### PR DESCRIPTION
**Pull request by gerasy1987**
As suggested in #364 the large objects in `summary.causal_model` are only included when requested explicitly. Also `inspect()` now requests these objects implicitly if needed. The size of default summary objects is significantly reduced, e.g.

```
> library(CausalQueries)
> 
> model <- make_model("A -> Y <- B; C-> Y", add_causal_types = FALSE)
> sum_model <- summary(model)
> sum_model_lg <- summary(model, include = "prior_distribution")
> 
> sapply(
+   c("model",
+     "sum_model",
+     "sum_model_lg"),
+   function(x) {
+     object.size(get(x))
+   })
       model    sum_model sum_model_lg 
       82256       161104      8579280 
```

### CODE REVIEW

**Comment by macartan** [comment]
THANK YOU

**Comment by gerasy1987** [comment]
close #364

**Comment by macartan** [comment]
Hi Gosha --

Thanks for this.

I don't think arguments are getting passed to functions that require
arguments:

> inspect(model, "prior_hyperparameters", nodes = "X")


Think there's a simple fix

Also slightly worried that the posterior objects in the model summary by
default mean that the summary is as big as the model. Is that a worry?

**Comment by gerasy1987** [comment]
@macartan Yes, I forgot to check on passing arguments functionality. I am a bit short on time this week, but I am happy to look into it towards the end of the week.

On the summary object size, I noticed that for updated models, the posterior objects can be large as well. I prefer to preserve the original summarized object structure in summary, but also, looking at essential estimation functions (like `lm`), it does seem that the `summary` methods for those classes lose the raw data outputs, suggesting we can drop posterior objects and only preserve the necessary ones unless users request them. This should be an easy fix similar to what I have done already. I am not sure how big of a concern large summary objects are (as opposed to the cases I just addressed where summary takes time to compute) since the underlying `causal_model` objects will inevitably be large.

**Comment by macartan** [comment]
sounds good!

dots issue is fine; small fix;
one other fix (which I think I did before so want to be sure we are in line
on this): for stanfit we will print x$stan_objects$stanfit not
x$stan_objects
in the paper we describe accessing the raw fit with its own (unrenamed) vars

**Pull request merged**
